name: GitHub Actions Demo

run-name: GH Action Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
      - cron:  '15 6 * * 0'
  workflow_dispatch:  
    inputs:
      myenvironment:
        description: 'environment to be used for depoyment:'
        type: environment
        required: true
        
    
jobs:
  Build:
    name: Job_Build
    runs-on: ubuntu-latest
    steps:
      - name: Print Name of the GH event and branch
        run: |
          echo "Triggered event: ${{ github.event_name }}"
          echo "Name of branch: ${{ github.ref }}"

      - name: Perform checkout of the repository
        uses: actions/checkout@v4.1.2
      
      - name: List files in the repository
        run: |
          echo "Files present in the directory:"
          tree
          
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: |
          echo "Testing..."

  Load_Tests:    
    name: Load_Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load_Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15

  Production:
    name: Production
    runs-on: ubuntu-latest
    if: github.event.inputs.myenvironment == 'Production'
    needs: [ Tests, Load_Tests ]
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
         echo "Step 1 deploying..."
         sleep 10
      - run: |
         echo "Step 2 deploying..."
         sleep 10
      - run: |
         echo "Step 3 deploying..."
         sleep 10
     
